version: "3"

services:
  frontend:
    build: ./frontend/
    container_name: frontend
    networks:
      - pilot-network
    ports:
      - "8000:8000"
    depends_on:
      - backend
  backend:
    build: ./backend/
    container_name: backend
    networks:
      - pilot-network
    ports:
      - "8001:8001"

networks:
  pilot-network:
    ipam:
      driver: default
